layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 30
  exclude:
    forks: false
    projects:
      - personal-website

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  linkedin: tonybrix
  # medium: @your_username
  stackoverflow: 806777
  twitter: tonybrix
  # youtube: your_username
  website: https://tony.brix.ninja

topics:
  - name: Node
    web_url: https://github.com/topics/nodejs
    image_url: https://raw.githubusercontent.com/github/explore/fd96fceccf8c42c99cbe29cf0f8dcc4736fcb85a/topics/nodejs/nodejs.png

  - name: Atom
    web_url: https://github.com/topics/atom
    image_url: https://raw.githubusercontent.com/github/explore/c01f72d18e4f3dcb6ed83cb1a40d5a7fc0c0ddb2/topics/atom/atom.png

  - name: Git
    web_url: https://github.com/topics/git
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/git/git.png
